//created on: May 29, 2022
package integracija

//list any import classes here.

import sbnz.integracija.example.facts.Soil;
import sbnz.integracija.example.facts.Fertilizer;
import sbnz.integracija.example.OperationService;
import java.util.ArrayList;

//declare any global variables here
global OperationService operationService;
global ArrayList plants;


rule "Recommend NPK proportion"
	salience 2
    when
        $soil: Soil($kgn: kgN, $kgp: kgP , $kgk: kgK, plant.equals("") == false)
        $list: ArrayList( size > 0) from collect(
        	Fertilizer()
        )
        
        $f: Fertilizer() from operationService.getOptimalFertilizer($list, $kgp, $kgk)
    then
    	$soil.setFertilizer($f);
        $soil.setRecommendation($soil.getRecommendation() + "Fertilizer: " + $f.getName());
		
		update($soil);
		
end

rule "Calculate kilograms of fertilizer"
    salience 1
    when
        $soil: Soil( plant.equals("") == false)
        String(length() > 0) from $soil.getFertilizer().getName()
        $fertMass: Integer() from operationService.calculateMassRecommendation($soil)
    then
        $soil.setRecommendation($soil.getRecommendation() + " " + $fertMass + "kg");
        update($soil);

end
