//created on: May 29, 2022
package integracija

//list any import classes here.

import sbnz.integracija.example.facts.Soil;
import sbnz.integracija.example.facts.Fertilizer;
import sbnz.integracija.example.OperationService;
import java.util.ArrayList;

//declare any global variables here
global OperationService operationService;



rule "Recommend NPK proportion"
	salience 1
    when
        $soil: Soil($kgn: kgN, $kgp: kgP , $kgk: kgK)
        $list: ArrayList( size > 0) from collect(
        	Fertilizer()
        )
        
        $f: Fertilizer() from operationService.getOptimalFertilizer($list, $kgp, $kgk)
    then
    	
        $soil.setRecommendation($soil.getRecommendation() + "moze nesto: " + $f.getName());
		update($soil);
		
end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
